### ISSUE TITLE
Use / format for id params

### ISSUE THREAD

**Issue by adamf321** [moxie-leean/ng-cms#25]
The REST API expects an id to passed with the slash format, eg `http://example.dev/wp-json/wp/v2/posts/10` (`http://example.dev/wp-json/wp/v2/posts?id=10` won't work as expected).

I think we can automatically use this format for any parameter called `id` (it's quite standard to use this method).

**Comment by mitogh** [comment]
This methodology is called `REST`  and should do a couple things.
- Work and response based on the `HTTP` verb send by the request.
- Increase the version of the API from `v1` to `v2` so old applications can operate with no breaking changes on `v1` of the endpoints.

**Comment by adamf321** [comment]
This doesn't affect the endpoint version. Do you mean we should increment the version to 2 for the routes endpoint?

**Comment by mitogh** [comment]
Yes all the ones that are going to work with REST should change from v1 to v2 in order to allow backwards compatibility on either of those versions instead of introduce the changes on v1. That’s why each endpoint has the version numbers in order to allow space to introduce changes that are not compatible.

> If you ever need to break compatibility with new endpoints, you can then bump this to v2..

Ref. http://v2.wp-api.org/extending/adding/#namespacing http://v2.wp-api.org/extending/adding/#namespacing

**Comment by adamf321** [comment]
Yes, but this is the frontend. The backend will use a different endpoint namespace altogether, `wp` : /wp-json/wp/v2/posts. Agree the frontend modules could jump a major version so ng-cms moves to v1.0.0

**Comment by mitogh** [comment]
Correct. I think this should be editable via a `callback` to allow flexibility as happens with `$.get` from `jQuery`
